version: '3.7'
services:
  api-server:
    container_name: 'api-server'
    build: ./api
    env_file:
      - .env
      - ./api/.env
    ports:
      - '3001:${API_PORT}'

  web-server:
    container_name: 'web-server'
    build:
      context: ./web
      args:
        - 'REACT_APP_API_URL=${API_URL}:${API_PORT}'
    ports:
      - '3000:80'
    depends_on:
      - api-server